// ============================================
// DADOS DE TODAS AS LOTERIAS
// ============================================

export interface LotteryConfig {
  slug: string
  name: string
  country: string
  countryCode: string
  flag: string
  emoji: string
  gradient: string
  color: string
  mainNumbers: number
  mainRange: [number, number]
  extraNumbers: number
  extraRange: [number, number]
  extraName: string
  extraColor: 'red' | 'gold' | 'green' | 'blue' | 'purple'
  pricePerBet: number
  currency: string
  drawDays: string[]
  drawTime: string
  timezone: string
  description: string
  howToPlay: string
  jackpotStart: string
  odds: string
  apiName?: string
  isBrazilian: boolean
}

export const LOTTERIES: LotteryConfig[] = [

  // ========================================
  // 🇧🇷 BRASILEIRAS
  // ========================================
  {
    slug: 'mega-sena',
    name: 'Mega-Sena',
    country: 'Brasil',
    countryCode: 'BR',
    flag: '🇧🇷',
    emoji: '🍀',
    gradient: 'linear-gradient(135deg, #009c3b, #00c74d)',
    color: '#009c3b',
    mainNumbers: 6,
    mainRange: [1, 60],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 5.00,
    currency: 'BRL',
    drawDays: ['terça', 'quinta', 'sábado'],
    drawTime: '20:00',
    timezone: 'America/Sao_Paulo',
    description: 'A maior loteria do Brasil! Escolha 6 números de 1 a 60.',
    howToPlay: 'Escolha 6 números de 1 a 60. Acerte 4, 5 ou 6 para ganhar.',
    jackpotStart: 'R$ 3.000.000',
    odds: '1 em 50.063.860',
    apiName: 'megasena',
    isBrazilian: true,
  },
  {
    slug: 'lotofacil',
    name: 'Lotofácil',
    country: 'Brasil',
    countryCode: 'BR',
    flag: '🇧🇷',
    emoji: '⭐',
    gradient: 'linear-gradient(135deg, #8b5cf6, #a78bfa)',
    color: '#8b5cf6',
    mainNumbers: 15,
    mainRange: [1, 25],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 3.00,
    currency: 'BRL',
    drawDays: ['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado'],
    drawTime: '20:00',
    timezone: 'America/Sao_Paulo',
    description: 'A loteria mais fácil de ganhar! Escolha 15 números de 1 a 25.',
    howToPlay: 'Escolha 15 números de 1 a 25. Ganha com 11 a 15 acertos!',
    jackpotStart: 'R$ 1.700.000',
    odds: '1 em 3.268.760',
    apiName: 'lotofacil',
    isBrazilian: true,
  },
  {
    slug: 'quina',
    name: 'Quina',
    country: 'Brasil',
    countryCode: 'BR',
    flag: '🇧🇷',
    emoji: '🔵',
    gradient: 'linear-gradient(135deg, #2563eb, #3b82f6)',
    color: '#2563eb',
    mainNumbers: 5,
    mainRange: [1, 80],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 2.50,
    currency: 'BRL',
    drawDays: ['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado'],
    drawTime: '20:00',
    timezone: 'America/Sao_Paulo',
    description: 'Sorteios diários! Escolha 5 números de 1 a 80.',
    howToPlay: 'Escolha 5 números de 1 a 80. Prêmios para 2 a 5 acertos.',
    jackpotStart: 'R$ 700.000',
    odds: '1 em 24.040.016',
    apiName: 'quina',
    isBrazilian: true,
  },
  {
    slug: 'lotomania',
    name: 'Lotomania',
    country: 'Brasil',
    countryCode: 'BR',
    flag: '🇧🇷',
    emoji: '🎪',
    gradient: 'linear-gradient(135deg, #f97316, #fb923c)',
    color: '#f97316',
    mainNumbers: 50,
    mainRange: [0, 99],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 3.00,
    currency: 'BRL',
    drawDays: ['terça', 'sexta'],
    drawTime: '20:00',
    timezone: 'America/Sao_Paulo',
    description: 'Escolha 50 números de 0 a 99!',
    howToPlay: 'Escolha 50 números de 0 a 99. São sorteados 20. Prêmios de 15 a 20 acertos e 0 acertos!',
    jackpotStart: 'R$ 1.000.000',
    odds: '1 em 11.372.635',
    apiName: 'lotomania',
    isBrazilian: true,
  },
  {
    slug: 'timemania',
    name: 'Timemania',
    country: 'Brasil',
    countryCode: 'BR',
    flag: '🇧🇷',
    emoji: '⚽',
    gradient: 'linear-gradient(135deg, #ef4444, #f87171)',
    color: '#ef4444',
    mainNumbers: 10,
    mainRange: [1, 80],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 3.50,
    currency: 'BRL',
    drawDays: ['terça', 'quinta', 'sábado'],
    drawTime: '20:00',
    timezone: 'America/Sao_Paulo',
    description: 'A loteria do futebol! Escolha 10 números e um time.',
    howToPlay: 'Escolha 10 números de 1 a 80 e um time do coração.',
    jackpotStart: 'R$ 500.000',
    odds: '1 em 26.472.637',
    apiName: 'timemania',
    isBrazilian: true,
  },
  {
    slug: 'dupla-sena',
    name: 'Dupla Sena',
    country: 'Brasil',
    countryCode: 'BR',
    flag: '🇧🇷',
    emoji: '🎲',
    gradient: 'linear-gradient(135deg, #dc2626, #b91c1c)',
    color: '#dc2626',
    mainNumbers: 6,
    mainRange: [1, 50],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 2.50,
    currency: 'BRL',
    drawDays: ['terça', 'quinta', 'sábado'],
    drawTime: '20:00',
    timezone: 'America/Sao_Paulo',
    description: 'Duas chances de ganhar no mesmo concurso!',
    howToPlay: 'Escolha 6 números de 1 a 50. Dois sorteios por concurso!',
    jackpotStart: 'R$ 500.000',
    odds: '1 em 15.890.700',
    apiName: 'duplasena',
    isBrazilian: true,
  },
  {
    slug: 'dia-de-sorte',
    name: 'Dia de Sorte',
    country: 'Brasil',
    countryCode: 'BR',
    flag: '🇧🇷',
    emoji: '☀️',
    gradient: 'linear-gradient(135deg, #eab308, #facc15)',
    color: '#eab308',
    mainNumbers: 7,
    mainRange: [1, 31],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 2.50,
    currency: 'BRL',
    drawDays: ['terça', 'quinta', 'sábado'],
    drawTime: '20:00',
    timezone: 'America/Sao_Paulo',
    description: 'Escolha 7 números e um mês da sorte!',
    howToPlay: 'Escolha 7 números de 1 a 31 e um mês da sorte.',
    jackpotStart: 'R$ 300.000',
    odds: '1 em 2.629.575',
    apiName: 'diadesorte',
    isBrazilian: true,
  },

  // ========================================
  // 🇺🇸 ESTADOS UNIDOS
  // ========================================
  {
    slug: 'mega-millions',
    name: 'Mega Millions',
    country: 'E.U.A.',
    countryCode: 'US',
    flag: '🇺🇸',
    emoji: '💰',
    gradient: 'linear-gradient(135deg, #1d4ed8, #2563eb)',
    color: '#1d4ed8',
    mainNumbers: 5,
    mainRange: [1, 70],
    extraNumbers: 1,
    extraRange: [1, 25],
    extraName: 'Mega Ball',
    extraColor: 'gold',
    pricePerBet: 15.00,
    currency: 'BRL',
    drawDays: ['terça', 'sexta'],
    drawTime: '01:00',
    timezone: 'America/New_York',
    description: 'Jackpots recordes de mais de US$ 1 bilhão!',
    howToPlay: 'Escolha 5 números de 1 a 70 e 1 Mega Ball de 1 a 25.',
    jackpotStart: 'US$ 20.000.000',
    odds: '1 em 302.575.350',
    isBrazilian: false,
  },
  {
    slug: 'powerball',
    name: 'Powerball',
    country: 'E.U.A.',
    countryCode: 'US',
    flag: '🇺🇸',
    emoji: '💥',
    gradient: 'linear-gradient(135deg, #dc2626, #ef4444)',
    color: '#dc2626',
    mainNumbers: 5,
    mainRange: [1, 69],
    extraNumbers: 1,
    extraRange: [1, 26],
    extraName: 'Powerball',
    extraColor: 'red',
    pricePerBet: 15.00,
    currency: 'BRL',
    drawDays: ['segunda', 'quarta', 'sábado'],
    drawTime: '00:59',
    timezone: 'America/New_York',
    description: 'A loteria mais famosa do mundo! Jackpots bilionários.',
    howToPlay: 'Escolha 5 números de 1 a 69 e 1 Powerball de 1 a 26.',
    jackpotStart: 'US$ 20.000.000',
    odds: '1 em 292.201.338',
    isBrazilian: false,
  },

  // ========================================
  // 🇦🇺 AUSTRÁLIA
  // ========================================
  {
    slug: 'oz-lotto',
    name: 'Oz Lotto',
    country: 'Austrália',
    countryCode: 'AU',
    flag: '🇦🇺',
    emoji: '🦘',
    gradient: 'linear-gradient(135deg, #0891b2, #06b6d4)',
    color: '#0891b2',
    mainNumbers: 7,
    mainRange: [1, 47],
    extraNumbers: 2,
    extraRange: [1, 47],
    extraName: 'Suplementar',
    extraColor: 'blue',
    pricePerBet: 8.00,
    currency: 'BRL',
    drawDays: ['terça'],
    drawTime: '07:30',
    timezone: 'Australia/Sydney',
    description: 'A grande loteria australiana! 7 números de 1 a 47.',
    howToPlay: 'Escolha 7 números de 1 a 47. 2 suplementares para prêmios secundários.',
    jackpotStart: 'A$ 2.000.000',
    odds: '1 em 45.379.620',
    isBrazilian: false,
  },
  {
    slug: 'au-powerball',
    name: 'Powerball Lotto',
    country: 'Austrália',
    countryCode: 'AU',
    flag: '🇦🇺',
    emoji: '⚡',
    gradient: 'linear-gradient(135deg, #7c3aed, #8b5cf6)',
    color: '#7c3aed',
    mainNumbers: 7,
    mainRange: [1, 35],
    extraNumbers: 1,
    extraRange: [1, 20],
    extraName: 'Powerball',
    extraColor: 'red',
    pricePerBet: 8.00,
    currency: 'BRL',
    drawDays: ['quinta'],
    drawTime: '07:30',
    timezone: 'Australia/Sydney',
    description: 'Powerball australiano com jackpots enormes!',
    howToPlay: 'Escolha 7 números de 1 a 35 e 1 Powerball de 1 a 20.',
    jackpotStart: 'A$ 3.000.000',
    odds: '1 em 134.490.400',
    isBrazilian: false,
  },
  {
    slug: 'saturday-lotto',
    name: 'Saturday Lotto',
    country: 'Austrália',
    countryCode: 'AU',
    flag: '🇦🇺',
    emoji: '🎉',
    gradient: 'linear-gradient(135deg, #ea580c, #f97316)',
    color: '#ea580c',
    mainNumbers: 6,
    mainRange: [1, 45],
    extraNumbers: 2,
    extraRange: [1, 45],
    extraName: 'Suplementar',
    extraColor: 'gold',
    pricePerBet: 6.00,
    currency: 'BRL',
    drawDays: ['sábado'],
    drawTime: '07:30',
    timezone: 'Australia/Sydney',
    description: 'Loteria clássica australiana de sábado!',
    howToPlay: 'Escolha 6 números de 1 a 45. 2 suplementares para prêmios secundários.',
    jackpotStart: 'A$ 4.000.000',
    odds: '1 em 8.145.060',
    isBrazilian: false,
  },
  {
    slug: 'saturday-lotto-super',
    name: 'Supersorteio Saturday Lotto',
    country: 'Austrália',
    countryCode: 'AU',
    flag: '🇦🇺',
    emoji: '🌟',
    gradient: 'linear-gradient(135deg, #b45309, #d97706)',
    color: '#b45309',
    mainNumbers: 6,
    mainRange: [1, 45],
    extraNumbers: 2,
    extraRange: [1, 45],
    extraName: 'Suplementar',
    extraColor: 'gold',
    pricePerBet: 8.00,
    currency: 'BRL',
    drawDays: ['sábado'],
    drawTime: '07:30',
    timezone: 'Australia/Sydney',
    description: 'Supersorteio especial com jackpots maiores!',
    howToPlay: 'Escolha 6 números de 1 a 45. Jackpots especiais até A$ 20 milhões!',
    jackpotStart: 'A$ 20.000.000',
    odds: '1 em 8.145.060',
    isBrazilian: false,
  },
  {
    slug: 'weekday-windfall',
    name: 'Weekday Windfall',
    country: 'Austrália',
    countryCode: 'AU',
    flag: '🇦🇺',
    emoji: '💨',
    gradient: 'linear-gradient(135deg, #16a34a, #22c55e)',
    color: '#16a34a',
    mainNumbers: 6,
    mainRange: [1, 45],
    extraNumbers: 2,
    extraRange: [1, 45],
    extraName: 'Suplementar',
    extraColor: 'green',
    pricePerBet: 6.00,
    currency: 'BRL',
    drawDays: ['quarta'],
    drawTime: '07:30',
    timezone: 'Australia/Sydney',
    description: 'Loteria australiana com sorteios durante a semana!',
    howToPlay: 'Escolha 6 números de 1 a 45. 2 suplementares para prêmios secundários.',
    jackpotStart: 'A$ 1.000.000',
    odds: '1 em 8.145.060',
    isBrazilian: false,
  },

  // ========================================
  // 🇨🇦 CANADÁ
  // ========================================
  {
    slug: 'lotto-649',
    name: 'Lotto 6/49',
    country: 'Canadá',
    countryCode: 'CA',
    flag: '🇨🇦',
    emoji: '🍁',
    gradient: 'linear-gradient(135deg, #dc2626, #ef4444)',
    color: '#dc2626',
    mainNumbers: 6,
    mainRange: [1, 49],
    extraNumbers: 1,
    extraRange: [1, 49],
    extraName: 'Bonus',
    extraColor: 'gold',
    pricePerBet: 8.00,
    currency: 'BRL',
    drawDays: ['quarta', 'sábado'],
    drawTime: '00:30',
    timezone: 'America/Toronto',
    description: 'A clássica loteria canadense 6/49!',
    howToPlay: 'Escolha 6 números de 1 a 49. Número Bonus para prêmios extras.',
    jackpotStart: 'CA$ 5.000.000',
    odds: '1 em 13.983.816',
    isBrazilian: false,
  },
  {
    slug: 'ontario-49',
    name: 'Ontario 49',
    country: 'Canadá',
    countryCode: 'CA',
    flag: '🇨🇦',
    emoji: '🏒',
    gradient: 'linear-gradient(135deg, #0369a1, #0284c7)',
    color: '#0369a1',
    mainNumbers: 6,
    mainRange: [1, 49],
    extraNumbers: 1,
    extraRange: [1, 49],
    extraName: 'Bonus',
    extraColor: 'blue',
    pricePerBet: 6.00,
    currency: 'BRL',
    drawDays: ['quarta', 'sábado'],
    drawTime: '00:30',
    timezone: 'America/Toronto',
    description: 'Loteria exclusiva de Ontario, Canadá.',
    howToPlay: 'Escolha 6 números de 1 a 49.',
    jackpotStart: 'CA$ 2.000.000',
    odds: '1 em 13.983.816',
    isBrazilian: false,
  },

  // ========================================
  // 🇪🇸 ESPANHA
  // ========================================
  {
    slug: 'bonoloto',
    name: 'BonoLoto',
    country: 'Espanha',
    countryCode: 'ES',
    flag: '🇪🇸',
    emoji: '🌞',
    gradient: 'linear-gradient(135deg, #dc2626, #fbbf24)',
    color: '#dc2626',
    mainNumbers: 6,
    mainRange: [1, 49],
    extraNumbers: 1,
    extraRange: [0, 9],
    extraName: 'Reintegro',
    extraColor: 'gold',
    pricePerBet: 5.00,
    currency: 'BRL',
    drawDays: ['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado'],
    drawTime: '17:30',
    timezone: 'Europe/Madrid',
    description: 'Loteria diária espanhola com sorteios 6 dias por semana!',
    howToPlay: 'Escolha 6 números de 1 a 49. Reintegro (0-9) devolve o valor da aposta.',
    jackpotStart: '€ 400.000',
    odds: '1 em 13.983.816',
    isBrazilian: false,
  },
  {
    slug: 'el-gordo',
    name: 'El Gordo',
    country: 'Espanha',
    countryCode: 'ES',
    flag: '🇪🇸',
    emoji: '🎊',
    gradient: 'linear-gradient(135deg, #b91c1c, #dc2626)',
    color: '#b91c1c',
    mainNumbers: 5,
    mainRange: [1, 54],
    extraNumbers: 1,
    extraRange: [0, 9],
    extraName: 'Número Chave',
    extraColor: 'red',
    pricePerBet: 8.00,
    currency: 'BRL',
    drawDays: ['domingo'],
    drawTime: '17:30',
    timezone: 'Europe/Madrid',
    description: 'El Gordo da Primitiva — prêmios incríveis!',
    howToPlay: 'Escolha 5 números de 1 a 54 e 1 Número Chave de 0 a 9.',
    jackpotStart: '€ 5.000.000',
    odds: '1 em 31.625.100',
    isBrazilian: false,
  },
  {
    slug: 'la-primitiva',
    name: 'La Primitiva',
    country: 'Espanha',
    countryCode: 'ES',
    flag: '🇪🇸',
    emoji: '👑',
    gradient: 'linear-gradient(135deg, #059669, #10b981)',
    color: '#059669',
    mainNumbers: 6,
    mainRange: [1, 49],
    extraNumbers: 1,
    extraRange: [0, 9],
    extraName: 'Reintegro',
    extraColor: 'green',
    pricePerBet: 6.00,
    currency: 'BRL',
    drawDays: ['quinta', 'sábado'],
    drawTime: '17:40',
    timezone: 'Europe/Madrid',
    description: 'Uma das loterias mais antigas da Espanha!',
    howToPlay: 'Escolha 6 de 1 a 49. Complementário e Reintegro para prêmios extras.',
    jackpotStart: '€ 1.000.000',
    odds: '1 em 139.838.160',
    isBrazilian: false,
  },

  // ========================================
  // 🇪🇺 EUROPA
  // ========================================
  {
    slug: 'euromilhoes',
    name: 'EuroMilhões',
    country: 'Europa',
    countryCode: 'EU',
    flag: '🇪🇺',
    emoji: '⭐',
    gradient: 'linear-gradient(135deg, #0369a1, #0ea5e9)',
    color: '#0369a1',
    mainNumbers: 5,
    mainRange: [1, 50],
    extraNumbers: 2,
    extraRange: [1, 12],
    extraName: 'Estrela',
    extraColor: 'gold',
    pricePerBet: 15.00,
    currency: 'BRL',
    drawDays: ['terça', 'sexta'],
    drawTime: '17:00',
    timezone: 'Europe/Lisbon',
    description: 'A maior loteria da Europa! Jogada em 9 países.',
    howToPlay: 'Escolha 5 números de 1 a 50 e 2 Estrelas de 1 a 12.',
    jackpotStart: '€ 17.000.000',
    odds: '1 em 139.838.160',
    isBrazilian: false,
  },
  {
    slug: 'euromilhoes-super',
    name: 'Supersorteio EuroMilhões',
    country: 'Europa',
    countryCode: 'EU',
    flag: '🇪🇺',
    emoji: '💫',
    gradient: 'linear-gradient(135deg, #4338ca, #6366f1)',
    color: '#4338ca',
    mainNumbers: 5,
    mainRange: [1, 50],
    extraNumbers: 2,
    extraRange: [1, 12],
    extraName: 'Estrela',
    extraColor: 'gold',
    pricePerBet: 18.00,
    currency: 'BRL',
    drawDays: ['sexta'],
    drawTime: '16:00',
    timezone: 'Europe/Lisbon',
    description: 'Supersorteio especial com jackpot garantido de € 130 milhões!',
    howToPlay: 'Mesmas regras do EuroMilhões com jackpots especiais!',
    jackpotStart: '€ 130.000.000',
    odds: '1 em 139.838.160',
    isBrazilian: false,
  },
  {
    slug: 'eurojackpot',
    name: 'EuroJackpot',
    country: 'Europa',
    countryCode: 'EU',
    flag: '🇪🇺',
    emoji: '🏆',
    gradient: 'linear-gradient(135deg, #b45309, #d97706)',
    color: '#b45309',
    mainNumbers: 5,
    mainRange: [1, 50],
    extraNumbers: 2,
    extraRange: [1, 12],
    extraName: 'Euro Number',
    extraColor: 'gold',
    pricePerBet: 12.00,
    currency: 'BRL',
    drawDays: ['terça', 'sexta'],
    drawTime: '17:00',
    timezone: 'Europe/Berlin',
    description: 'Loteria pan-europeia jogada em 18 países!',
    howToPlay: 'Escolha 5 números de 1 a 50 e 2 Euro Numbers de 1 a 12.',
    jackpotStart: '€ 10.000.000',
    odds: '1 em 139.838.160',
    isBrazilian: false,
  },
  {
    slug: 'eurodreams',
    name: 'EuroDreams',
    country: 'Europa',
    countryCode: 'EU',
    flag: '🇪🇺',
    emoji: '🌙',
    gradient: 'linear-gradient(135deg, #6d28d9, #8b5cf6)',
    color: '#6d28d9',
    mainNumbers: 6,
    mainRange: [1, 40],
    extraNumbers: 1,
    extraRange: [1, 5],
    extraName: 'Dream',
    extraColor: 'purple',
    pricePerBet: 12.00,
    currency: 'BRL',
    drawDays: ['segunda', 'quinta'],
    drawTime: '17:00',
    timezone: 'Europe/Paris',
    description: 'Ganhe € 20.000 por mês durante 30 anos!',
    howToPlay: 'Escolha 6 números de 1 a 40 e 1 Dream de 1 a 5. Prêmio: renda vitalícia!',
    jackpotStart: '€ 20.000/mês',
    odds: '1 em 19.191.900',
    isBrazilian: false,
  },

  // ========================================
  // 🇫🇷 FRANÇA
  // ========================================
  {
    slug: 'france-loto',
    name: 'Loto',
    country: 'França',
    countryCode: 'FR',
    flag: '🇫🇷',
    emoji: '🗼',
    gradient: 'linear-gradient(135deg, #1d4ed8, #3b82f6)',
    color: '#1d4ed8',
    mainNumbers: 5,
    mainRange: [1, 49],
    extraNumbers: 1,
    extraRange: [1, 10],
    extraName: 'Chance',
    extraColor: 'red',
    pricePerBet: 8.00,
    currency: 'BRL',
    drawDays: ['segunda', 'quarta', 'sábado'],
    drawTime: '16:35',
    timezone: 'Europe/Paris',
    description: 'A loteria francesa com jackpots milionários!',
    howToPlay: 'Escolha 5 números de 1 a 49 e 1 número Chance de 1 a 10.',
    jackpotStart: '€ 2.000.000',
    odds: '1 em 19.068.840',
    isBrazilian: false,
  },

  // ========================================
  // 🇵🇹 PORTUGAL
  // ========================================
  {
    slug: 'totoloto',
    name: 'Totoloto',
    country: 'Portugal',
    countryCode: 'PT',
    flag: '🇵🇹',
    emoji: '🐓',
    gradient: 'linear-gradient(135deg, #059669, #10b981)',
    color: '#059669',
    mainNumbers: 5,
    mainRange: [1, 49],
    extraNumbers: 2,
    extraRange: [1, 49],
    extraName: 'Extra',
    extraColor: 'green',
    pricePerBet: 6.00,
    currency: 'BRL',
    drawDays: ['quarta', 'sexta'],
    drawTime: '19:00',
    timezone: 'Europe/Lisbon',
    description: 'A loteria clássica de Portugal!',
    howToPlay: 'Escolha 5 números de 1 a 49 e 2 extras.',
    jackpotStart: '€ 1.000.000',
    odds: '1 em 13.983.816',
    isBrazilian: false,
  },

  // ========================================
  // 🇮🇹 ITÁLIA
  // ========================================
  {
    slug: 'superenalotto',
    name: 'SuperEnalotto',
    country: 'Itália',
    countryCode: 'IT',
    flag: '🇮🇹',
    emoji: '🍕',
    gradient: 'linear-gradient(135deg, #059669, #10b981)',
    color: '#059669',
    mainNumbers: 6,
    mainRange: [1, 90],
    extraNumbers: 1,
    extraRange: [1, 90],
    extraName: 'Jolly',
    extraColor: 'green',
    pricePerBet: 10.00,
    currency: 'BRL',
    drawDays: ['terça', 'quinta', 'sábado'],
    drawTime: '20:00',
    timezone: 'Europe/Rome',
    description: 'A loteria italiana com os maiores jackpots da Europa!',
    howToPlay: 'Escolha 6 números de 1 a 90. O Jolly é sorteado separadamente.',
    jackpotStart: '€ 2.000.000',
    odds: '1 em 622.614.630',
    isBrazilian: false,
  },

  // ========================================
  // 🇬🇧 REINO UNIDO
  // ========================================
  {
    slug: 'uk-lotto',
    name: 'UK Lotto',
    country: 'Reino Unido',
    countryCode: 'GB',
    flag: '🇬🇧',
    emoji: '👑',
    gradient: 'linear-gradient(135deg, #4338ca, #6366f1)',
    color: '#4338ca',
    mainNumbers: 6,
    mainRange: [1, 59],
    extraNumbers: 1,
    extraRange: [1, 59],
    extraName: 'Bonus Ball',
    extraColor: 'blue',
    pricePerBet: 10.00,
    currency: 'BRL',
    drawDays: ['quarta', 'sábado'],
    drawTime: '20:00',
    timezone: 'Europe/London',
    description: 'A clássica loteria britânica!',
    howToPlay: 'Escolha 6 números de 1 a 59. Bonus Ball para prêmio secundário.',
    jackpotStart: '£ 2.000.000',
    odds: '1 em 45.057.474',
    isBrazilian: false,
  },

  // ========================================
  // 🇦🇹 ÁUSTRIA
  // ========================================
  {
    slug: 'austria-lotto',
    name: 'Lotto',
    country: 'Áustria',
    countryCode: 'AT',
    flag: '🇦🇹',
    emoji: '🏔️',
    gradient: 'linear-gradient(135deg, #dc2626, #ef4444)',
    color: '#dc2626',
    mainNumbers: 6,
    mainRange: [1, 45],
    extraNumbers: 1,
    extraRange: [1, 45],
    extraName: 'Zusatzzahl',
    extraColor: 'red',
    pricePerBet: 6.00,
    currency: 'BRL',
    drawDays: ['quarta', 'domingo'],
    drawTime: '14:47',
    timezone: 'Europe/Vienna',
    description: 'A loteria clássica da Áustria!',
    howToPlay: 'Escolha 6 números de 1 a 45. Zusatzzahl para prêmio adicional.',
    jackpotStart: '€ 1.000.000',
    odds: '1 em 8.145.060',
    isBrazilian: false,
  },

  // ========================================
  // 🇵🇭 FILIPINAS
  // ========================================
  {
    slug: 'ph-grandlotto',
    name: 'GrandLotto',
    country: 'Filipinas',
    countryCode: 'PH',
    flag: '🇵🇭',
    emoji: '🌴',
    gradient: 'linear-gradient(135deg, #1d4ed8, #2563eb)',
    color: '#1d4ed8',
    mainNumbers: 6,
    mainRange: [1, 55],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'blue',
    pricePerBet: 4.00,
    currency: 'BRL',
    drawDays: ['segunda', 'quarta', 'sábado'],
    drawTime: '10:00',
    timezone: 'Asia/Manila',
    description: 'A maior loteria das Filipinas! 6/55.',
    howToPlay: 'Escolha 6 números de 1 a 55.',
    jackpotStart: '₱ 30.000.000',
    odds: '1 em 28.989.675',
    isBrazilian: false,
  },
  {
    slug: 'ph-lotto',
    name: 'Lotto',
    country: 'Filipinas',
    countryCode: 'PH',
    flag: '🇵🇭',
    emoji: '🎯',
    gradient: 'linear-gradient(135deg, #059669, #10b981)',
    color: '#059669',
    mainNumbers: 6,
    mainRange: [1, 42],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 3.00,
    currency: 'BRL',
    drawDays: ['terça', 'quinta', 'sábado'],
    drawTime: '10:00',
    timezone: 'Asia/Manila',
    description: 'Lotto 6/42 das Filipinas.',
    howToPlay: 'Escolha 6 números de 1 a 42.',
    jackpotStart: '₱ 6.000.000',
    odds: '1 em 5.245.786',
    isBrazilian: false,
  },
  {
    slug: 'ph-megalotto',
    name: 'Megalotto',
    country: 'Filipinas',
    countryCode: 'PH',
    flag: '🇵🇭',
    emoji: '🔥',
    gradient: 'linear-gradient(135deg, #b91c1c, #dc2626)',
    color: '#b91c1c',
    mainNumbers: 6,
    mainRange: [1, 45],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'red',
    pricePerBet: 3.00,
    currency: 'BRL',
    drawDays: ['segunda', 'quarta', 'sexta'],
    drawTime: '10:00',
    timezone: 'Asia/Manila',
    description: 'Megalotto 6/45 das Filipinas.',
    howToPlay: 'Escolha 6 números de 1 a 45.',
    jackpotStart: '₱ 9.000.000',
    odds: '1 em 8.145.060',
    isBrazilian: false,
  },
  {
    slug: 'ph-superlotto',
    name: 'Superlotto',
    country: 'Filipinas',
    countryCode: 'PH',
    flag: '🇵🇭',
    emoji: '💎',
    gradient: 'linear-gradient(135deg, #7c3aed, #8b5cf6)',
    color: '#7c3aed',
    mainNumbers: 6,
    mainRange: [1, 49],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'purple',
    pricePerBet: 3.00,
    currency: 'BRL',
    drawDays: ['terça', 'quinta', 'domingo'],
    drawTime: '10:00',
    timezone: 'Asia/Manila',
    description: 'Superlotto 6/49 das Filipinas.',
    howToPlay: 'Escolha 6 números de 1 a 49.',
    jackpotStart: '₱ 16.000.000',
    odds: '1 em 13.983.816',
    isBrazilian: false,
  },
  {
    slug: 'ph-ultralotto',
    name: 'UltraLotto',
    country: 'Filipinas',
    countryCode: 'PH',
    flag: '🇵🇭',
    emoji: '🌟',
    gradient: 'linear-gradient(135deg, #b45309, #d97706)',
    color: '#b45309',
    mainNumbers: 6,
    mainRange: [1, 58],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'gold',
    pricePerBet: 4.00,
    currency: 'BRL',
    drawDays: ['terça', 'sexta', 'domingo'],
    drawTime: '10:00',
    timezone: 'Asia/Manila',
    description: 'UltraLotto 6/58 — a maior das Filipinas!',
    howToPlay: 'Escolha 6 números de 1 a 58.',
    jackpotStart: '₱ 50.000.000',
    odds: '1 em 40.475.358',
    isBrazilian: false,
  },

  // ========================================
  // 🇯🇵 JAPÃO
  // ========================================
  {
    slug: 'jp-loto6',
    name: 'Loto 6',
    country: 'Japão',
    countryCode: 'JP',
    flag: '🇯🇵',
    emoji: '🎌',
    gradient: 'linear-gradient(135deg, #dc2626, #ef4444)',
    color: '#dc2626',
    mainNumbers: 6,
    mainRange: [1, 43],
    extraNumbers: 1,
    extraRange: [1, 43],
    extraName: 'Bonus',
    extraColor: 'red',
    pricePerBet: 5.00,
    currency: 'BRL',
    drawDays: ['segunda', 'quinta'],
    drawTime: '06:45',
    timezone: 'Asia/Tokyo',
    description: 'A loteria Loto 6 do Japão!',
    howToPlay: 'Escolha 6 números de 1 a 43. 1 Bonus para prêmio secundário.',
    jackpotStart: '¥ 200.000.000',
    odds: '1 em 6.096.454',
    isBrazilian: false,
  },
  {
    slug: 'jp-loto7',
    name: 'Loto 7',
    country: 'Japão',
    countryCode: 'JP',
    flag: '🇯🇵',
    emoji: '⛩️',
    gradient: 'linear-gradient(135deg, #0369a1, #0284c7)',
    color: '#0369a1',
    mainNumbers: 7,
    mainRange: [1, 37],
    extraNumbers: 2,
    extraRange: [1, 37],
    extraName: 'Bonus',
    extraColor: 'blue',
    pricePerBet: 6.00,
    currency: 'BRL',
    drawDays: ['sexta'],
    drawTime: '06:45',
    timezone: 'Asia/Tokyo',
    description: 'Loto 7 — a grande loteria japonesa!',
    howToPlay: 'Escolha 7 números de 1 a 37. 2 Bonus para prêmios extras.',
    jackpotStart: '¥ 600.000.000',
    odds: '1 em 10.295.472',
    isBrazilian: false,
  },
  {
    slug: 'jp-miniloto',
    name: 'Mini Loto',
    country: 'Japão',
    countryCode: 'JP',
    flag: '🇯🇵',
    emoji: '🌸',
    gradient: 'linear-gradient(135deg, #ec4899, #f472b6)',
    color: '#ec4899',
    mainNumbers: 5,
    mainRange: [1, 31],
    extraNumbers: 1,
    extraRange: [1, 31],
    extraName: 'Bonus',
    extraColor: 'red',
    pricePerBet: 4.00,
    currency: 'BRL',
    drawDays: ['terça'],
    drawTime: '06:45',
    timezone: 'Asia/Tokyo',
    description: 'Mini Loto — loteria compacta do Japão!',
    howToPlay: 'Escolha 5 números de 1 a 31.',
    jackpotStart: '¥ 10.000.000',
    odds: '1 em 169.911',
    isBrazilian: false,
  },

  // ========================================
  // 🇲🇽 MÉXICO
  // ========================================
  {
    slug: 'mexlotto',
    name: 'Mexlotto',
    country: 'México',
    countryCode: 'MX',
    flag: '🇲🇽',
    emoji: '🌮',
    gradient: 'linear-gradient(135deg, #059669, #10b981)',
    color: '#059669',
    mainNumbers: 6,
    mainRange: [1, 56],
    extraNumbers: 1,
    extraRange: [1, 56],
    extraName: 'Adicional',
    extraColor: 'gold',
    pricePerBet: 4.00,
    currency: 'BRL',
    drawDays: ['quarta', 'sábado'],
    drawTime: '00:15',
    timezone: 'America/Mexico_City',
    description: 'A loteria nacional do México!',
    howToPlay: 'Escolha 6 números de 1 a 56 e 1 Adicional.',
    jackpotStart: 'MX$ 40.000.000',
    odds: '1 em 32.468.436',
    isBrazilian: false,
  },
  {
    slug: 'mexlotto-vintage',
    name: 'Mexlotto Vintage',
    country: 'México',
    countryCode: 'MX',
    flag: '🇲🇽',
    emoji: '🎺',
    gradient: 'linear-gradient(135deg, #b45309, #d97706)',
    color: '#b45309',
    mainNumbers: 6,
    mainRange: [1, 39],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'gold',
    pricePerBet: 3.00,
    currency: 'BRL',
    drawDays: ['terça', 'sexta'],
    drawTime: '00:15',
    timezone: 'America/Mexico_City',
    description: 'Versão vintage da loteria mexicana!',
    howToPlay: 'Escolha 6 números de 1 a 39.',
    jackpotStart: 'MX$ 10.000.000',
    odds: '1 em 3.262.623',
    isBrazilian: false,
  },
  {
    slug: 'chispa-boom',
    name: 'Chispa Boom',
    country: 'México',
    countryCode: 'MX',
    flag: '🇲🇽',
    emoji: '💥',
    gradient: 'linear-gradient(135deg, #dc2626, #f97316)',
    color: '#dc2626',
    mainNumbers: 5,
    mainRange: [1, 24],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'red',
    pricePerBet: 2.00,
    currency: 'BRL',
    drawDays: ['segunda', 'quarta', 'sexta'],
    drawTime: '00:15',
    timezone: 'America/Mexico_City',
    description: 'Loteria rápida mexicana!',
    howToPlay: 'Escolha 5 números de 1 a 24.',
    jackpotStart: 'MX$ 5.000.000',
    odds: '1 em 42.504',
    isBrazilian: false,
  },
  {
    slug: 'triple-chance',
    name: 'Triple Chance Clásico',
    country: 'México',
    countryCode: 'MX',
    flag: '🇲🇽',
    emoji: '🎰',
    gradient: 'linear-gradient(135deg, #7c3aed, #a78bfa)',
    color: '#7c3aed',
    mainNumbers: 5,
    mainRange: [0, 9],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'purple',
    pricePerBet: 2.00,
    currency: 'BRL',
    drawDays: ['segunda', 'quarta', 'sexta'],
    drawTime: '00:00',
    timezone: 'America/Mexico_City',
    description: 'Triple Chance Clásico — loteria de dígitos mexicana!',
    howToPlay: 'Escolha 5 dígitos de 0 a 9.',
    jackpotStart: 'MX$ 1.000.000',
    odds: '1 em 100.000',
    isBrazilian: false,
  },

  // ========================================
  // 🇵🇪 PERU
  // ========================================
  {
    slug: 'kabala',
    name: 'Kábala',
    country: 'Peru',
    countryCode: 'PE',
    flag: '🇵🇪',
    emoji: '🔮',
    gradient: 'linear-gradient(135deg, #7c3aed, #a78bfa)',
    color: '#7c3aed',
    mainNumbers: 6,
    mainRange: [1, 43],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'purple',
    pricePerBet: 3.00,
    currency: 'BRL',
    drawDays: ['terça', 'quinta', 'sábado'],
    drawTime: '23:00',
    timezone: 'America/Lima',
    description: 'A loteria mística do Peru!',
    howToPlay: 'Escolha 6 números de 1 a 43.',
    jackpotStart: 'S/ 2.000.000',
    odds: '1 em 6.096.454',
    isBrazilian: false,
  },
  {
    slug: 'la-tinka',
    name: 'La Tinka',
    country: 'Peru',
    countryCode: 'PE',
    flag: '🇵🇪',
    emoji: '🎰',
    gradient: 'linear-gradient(135deg, #dc2626, #ef4444)',
    color: '#dc2626',
    mainNumbers: 6,
    mainRange: [1, 45],
    extraNumbers: 1,
    extraRange: [1, 45],
    extraName: 'Boliyapa',
    extraColor: 'red',
    pricePerBet: 3.00,
    currency: 'BRL',
    drawDays: ['quarta', 'domingo'],
    drawTime: '23:00',
    timezone: 'America/Lima',
    description: 'A maior loteria do Peru!',
    howToPlay: 'Escolha 6 números de 1 a 45 e 1 Boliyapa.',
    jackpotStart: 'S/ 4.000.000',
    odds: '1 em 8.145.060',
    isBrazilian: false,
  },

  // ========================================
  // 🇵🇱 POLÔNIA
  // ========================================
  {
    slug: 'pl-lotto',
    name: 'Lotto',
    country: 'Polônia',
    countryCode: 'PL',
    flag: '🇵🇱',
    emoji: '🦅',
    gradient: 'linear-gradient(135deg, #dc2626, #ef4444)',
    color: '#dc2626',
    mainNumbers: 6,
    mainRange: [1, 49],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'red',
    pricePerBet: 4.00,
    currency: 'BRL',
    drawDays: ['terça', 'quinta', 'sábado'],
    drawTime: '17:50',
    timezone: 'Europe/Warsaw',
    description: 'A loteria polonesa clássica!',
    howToPlay: 'Escolha 6 números de 1 a 49.',
    jackpotStart: 'zł 2.000.000',
    odds: '1 em 13.983.816',
    isBrazilian: false,
  },
  {
    slug: 'pl-minilotto',
    name: 'Mini Lotto',
    country: 'Polônia',
    countryCode: 'PL',
    flag: '🇵🇱',
    emoji: '🎯',
    gradient: 'linear-gradient(135deg, #0369a1, #0284c7)',
    color: '#0369a1',
    mainNumbers: 5,
    mainRange: [1, 42],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'blue',
    pricePerBet: 3.00,
    currency: 'BRL',
    drawDays: ['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado'],
    drawTime: '17:50',
    timezone: 'Europe/Warsaw',
    description: 'Sorteios diários na Polônia!',
    howToPlay: 'Escolha 5 números de 1 a 42.',
    jackpotStart: 'zł 400.000',
    odds: '1 em 850.668',
    isBrazilian: false,
  },

  // ========================================
  // 🇭🇺 HUNGRIA
  // ========================================
  {
    slug: 'hatoslotto',
    name: 'HatosLotto',
    country: 'Hungria',
    countryCode: 'HU',
    flag: '🇭🇺',
    emoji: '🏰',
    gradient: 'linear-gradient(135deg, #059669, #10b981)',
    color: '#059669',
    mainNumbers: 6,
    mainRange: [1, 45],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 4.00,
    currency: 'BRL',
    drawDays: ['domingo'],
    drawTime: '16:45',
    timezone: 'Europe/Budapest',
    description: 'Loteria húngara 6/45!',
    howToPlay: 'Escolha 6 números de 1 a 45.',
    jackpotStart: 'Ft 100.000.000',
    odds: '1 em 8.145.060',
    isBrazilian: false,
  },
  {
    slug: 'otoslotto',
    name: 'OtosLotto',
    country: 'Hungria',
    countryCode: 'HU',
    flag: '🇭🇺',
    emoji: '🎪',
    gradient: 'linear-gradient(135deg, #b45309, #d97706)',
    color: '#b45309',
    mainNumbers: 5,
    mainRange: [1, 90],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'gold',
    pricePerBet: 4.00,
    currency: 'BRL',
    drawDays: ['sábado'],
    drawTime: '14:45',
    timezone: 'Europe/Budapest',
    description: 'Loteria húngara 5/90 — a mais difícil!',
    howToPlay: 'Escolha 5 números de 1 a 90.',
    jackpotStart: 'Ft 500.000.000',
    odds: '1 em 43.949.268',
    isBrazilian: false,
  },

  // ========================================
  // 🇷🇴 ROMÊNIA
  // ========================================
  {
    slug: 'ro-joker',
    name: 'Joker',
    country: 'Romênia',
    countryCode: 'RO',
    flag: '🇷🇴',
    emoji: '🃏',
    gradient: 'linear-gradient(135deg, #dc2626, #ef4444)',
    color: '#dc2626',
    mainNumbers: 5,
    mainRange: [1, 45],
    extraNumbers: 1,
    extraRange: [1, 20],
    extraName: 'Joker',
    extraColor: 'red',
    pricePerBet: 4.00,
    currency: 'BRL',
    drawDays: ['quinta', 'domingo'],
    drawTime: '13:15',
    timezone: 'Europe/Bucharest',
    description: 'Loteria Joker da Romênia!',
    howToPlay: 'Escolha 5 números de 1 a 45 e 1 Joker de 1 a 20.',
    jackpotStart: 'RON 1.000.000',
    odds: '1 em 24.435.180',
    isBrazilian: false,
  },
  {
    slug: 'ro-loto649',
    name: 'Loto 6/49',
    country: 'Romênia',
    countryCode: 'RO',
    flag: '🇷🇴',
    emoji: '🎲',
    gradient: 'linear-gradient(135deg, #0369a1, #0284c7)',
    color: '#0369a1',
    mainNumbers: 6,
    mainRange: [1, 49],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'blue',
    pricePerBet: 3.00,
    currency: 'BRL',
    drawDays: ['quinta', 'domingo'],
    drawTime: '13:15',
    timezone: 'Europe/Bucharest',
    description: 'Loto 6/49 romena clássica!',
    howToPlay: 'Escolha 6 números de 1 a 49.',
    jackpotStart: 'RON 2.000.000',
    odds: '1 em 13.983.816',
    isBrazilian: false,
  },

  // ========================================
  // 🇿🇦 ÁFRICA DO SUL
  // ========================================
  {
    slug: 'za-lotto',
    name: 'Lotto',
    country: 'África do Sul',
    countryCode: 'ZA',
    flag: '🇿🇦',
    emoji: '🦁',
    gradient: 'linear-gradient(135deg, #059669, #10b981)',
    color: '#059669',
    mainNumbers: 6,
    mainRange: [1, 52],
    extraNumbers: 1,
    extraRange: [1, 52],
    extraName: 'Bonus',
    extraColor: 'green',
    pricePerBet: 3.00,
    currency: 'BRL',
    drawDays: ['quarta', 'sábado'],
    drawTime: '15:57',
    timezone: 'Africa/Johannesburg',
    description: 'A loteria sul-africana!',
    howToPlay: 'Escolha 6 números de 1 a 52. 1 Bonus Ball.',
    jackpotStart: 'R 2.000.000',
    odds: '1 em 20.358.520',
    isBrazilian: false,
  },
  {
    slug: 'za-powerball',
    name: 'PowerBall',
    country: 'África do Sul',
    countryCode: 'ZA',
    flag: '🇿🇦',
    emoji: '⚡',
    gradient: 'linear-gradient(135deg, #dc2626, #ef4444)',
    color: '#dc2626',
    mainNumbers: 5,
    mainRange: [1, 50],
    extraNumbers: 1,
    extraRange: [1, 20],
    extraName: 'PowerBall',
    extraColor: 'red',
    pricePerBet: 3.00,
    currency: 'BRL',
    drawDays: ['terça', 'sexta'],
    drawTime: '15:58',
    timezone: 'Africa/Johannesburg',
    description: 'PowerBall sul-africano!',
    howToPlay: 'Escolha 5 números de 1 a 50 e 1 PowerBall de 1 a 20.',
    jackpotStart: 'R 3.000.000',
    odds: '1 em 42.375.200',
    isBrazilian: false,
  },
  {
    slug: 'za-dailylotto',
    name: 'Daily Lotto',
    country: 'África do Sul',
    countryCode: 'ZA',
    flag: '🇿🇦',
    emoji: '☀️',
    gradient: 'linear-gradient(135deg, #f97316, #fb923c)',
    color: '#f97316',
    mainNumbers: 5,
    mainRange: [1, 36],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'gold',
    pricePerBet: 2.00,
    currency: 'BRL',
    drawDays: ['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado', 'domingo'],
    drawTime: '16:00',
    timezone: 'Africa/Johannesburg',
    description: 'Loteria diária da África do Sul!',
    howToPlay: 'Escolha 5 números de 1 a 36. Sorteios todos os dias!',
    jackpotStart: 'R 350.000',
    odds: '1 em 376.992',
    isBrazilian: false,
  },
]

// ========================================
// FUNÇÕES HELPER
// ========================================

export function getLotteryBySlug(slug: string): LotteryConfig | undefined {
  return LOTTERIES.find(l => l.slug === slug)
}

export function getBrazilianLotteries(): LotteryConfig[] {
  return LOTTERIES.filter(l => l.isBrazilian)
}

export function getInternationalLotteries(): LotteryConfig[] {
  return LOTTERIES.filter(l => !l.isBrazilian)
}

export function getLotteriesByCountry(): Record<string, LotteryConfig[]> {
  const grouped: Record<string, LotteryConfig[]> = {}
  LOTTERIES.filter(l => !l.isBrazilian).forEach(l => {
    if (!grouped[l.country]) grouped[l.country] = []
    grouped[l.country].push(l)
  })
  return grouped
}

export function formatCurrency(value: number, currency: string = 'BRL'): string {
  if (currency === 'BRL') return `R$ ${value.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`
  if (currency === 'USD') return `US$ ${value.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`
  if (currency === 'EUR') return `€ ${value.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`
  return `${value.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`
}
