// ============================================
// DADOS DE TODAS AS LOTERIAS
// ============================================

export interface LotteryConfig {
  slug: string
  name: string
  country: string
  countryCode: string
  flag: string
  emoji: string
  gradient: string
  color: string
  // Regras do jogo
  mainNumbers: number      // quantos números escolher
  mainRange: [number, number] // min e max
  extraNumbers: number     // números extras (powerball, estrela, etc)
  extraRange: [number, number]
  extraName: string        // "Powerball", "Mega Ball", "Estrela", etc
  extraColor: 'red' | 'gold' | 'green' | 'blue' | 'purple'
  // Preço e sorteio
  pricePerBet: number      // preço em BRL
  currency: string
  drawDays: string[]       // dias da semana
  drawTime: string         // horário
  timezone: string
  // Info
  description: string
  howToPlay: string
  jackpotStart: string
  odds: string
  // API
  apiName?: string         // nome na API da Caixa
  isBrazilian: boolean
}

export const LOTTERIES: LotteryConfig[] = [
  // ========== BRASILEIRAS ==========
  {
    slug: 'mega-sena',
    name: 'Mega-Sena',
    country: 'Brasil',
    countryCode: 'BR',
    flag: '🇧🇷',
    emoji: '🍀',
    gradient: 'linear-gradient(135deg, #009c3b, #00c74d)',
    color: '#009c3b',
    mainNumbers: 6,
    mainRange: [1, 60],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 5.00,
    currency: 'BRL',
    drawDays: ['terça', 'quinta', 'sábado'],
    drawTime: '20:00',
    timezone: 'America/Sao_Paulo',
    description: 'A maior loteria do Brasil! Escolha 6 números de 1 a 60 e concorra a prêmios milionários.',
    howToPlay: 'Escolha 6 números de 1 a 60. Se acertar todos os 6, ganha o prêmio principal. Também há prêmios para 4 e 5 acertos (Quadra e Quina).',
    jackpotStart: 'R$ 3.000.000',
    odds: '1 em 50.063.860',
    apiName: 'megasena',
    isBrazilian: true,
  },
  {
    slug: 'lotofacil',
    name: 'Lotofácil',
    country: 'Brasil',
    countryCode: 'BR',
    flag: '🇧🇷',
    emoji: '⭐',
    gradient: 'linear-gradient(135deg, #8b5cf6, #a78bfa)',
    color: '#8b5cf6',
    mainNumbers: 15,
    mainRange: [1, 25],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 3.00,
    currency: 'BRL',
    drawDays: ['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado'],
    drawTime: '20:00',
    timezone: 'America/Sao_Paulo',
    description: 'A loteria mais fácil de ganhar! Escolha 15 números de 1 a 25.',
    howToPlay: 'Escolha 15 números de 1 a 25. Ganha com 11, 12, 13, 14 ou 15 acertos. É a loteria com mais chances de premiação!',
    jackpotStart: 'R$ 1.700.000',
    odds: '1 em 3.268.760',
    apiName: 'lotofacil',
    isBrazilian: true,
  },
  {
    slug: 'quina',
    name: 'Quina',
    country: 'Brasil',
    countryCode: 'BR',
    flag: '🇧🇷',
    emoji: '🔵',
    gradient: 'linear-gradient(135deg, #2563eb, #3b82f6)',
    color: '#2563eb',
    mainNumbers: 5,
    mainRange: [1, 80],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 2.50,
    currency: 'BRL',
    drawDays: ['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado'],
    drawTime: '20:00',
    timezone: 'America/Sao_Paulo',
    description: 'Sorteios diários! Escolha 5 números de 1 a 80.',
    howToPlay: 'Escolha 5 números de 1 a 80. Prêmios para 2, 3, 4 ou 5 acertos.',
    jackpotStart: 'R$ 700.000',
    odds: '1 em 24.040.016',
    apiName: 'quina',
    isBrazilian: true,
  },
  {
    slug: 'lotomania',
    name: 'Lotomania',
    country: 'Brasil',
    countryCode: 'BR',
    flag: '🇧🇷',
    emoji: '🎪',
    gradient: 'linear-gradient(135deg, #f97316, #fb923c)',
    color: '#f97316',
    mainNumbers: 50,
    mainRange: [0, 99],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 3.00,
    currency: 'BRL',
    drawDays: ['terça', 'sexta'],
    drawTime: '20:00',
    timezone: 'America/Sao_Paulo',
    description: 'Escolha 50 números de 0 a 99! Quanto mais acertar, maior o prêmio.',
    howToPlay: 'Escolha 50 números de 0 a 99. São sorteados 20 números. Prêmios de 15 a 20 acertos, e também para 0 acertos!',
    jackpotStart: 'R$ 1.000.000',
    odds: '1 em 11.372.635',
    apiName: 'lotomania',
    isBrazilian: true,
  },
  {
    slug: 'timemania',
    name: 'Timemania',
    country: 'Brasil',
    countryCode: 'BR',
    flag: '🇧🇷',
    emoji: '⚽',
    gradient: 'linear-gradient(135deg, #ef4444, #f87171)',
    color: '#ef4444',
    mainNumbers: 10,
    mainRange: [1, 80],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 3.50,
    currency: 'BRL',
    drawDays: ['terça', 'quinta', 'sábado'],
    drawTime: '20:00',
    timezone: 'America/Sao_Paulo',
    description: 'A loteria do futebol! Escolha 10 números e um time do coração.',
    howToPlay: 'Escolha 10 números de 1 a 80 e um time de futebol. Prêmios para 3 a 7 acertos, mais prêmio pelo time.',
    jackpotStart: 'R$ 500.000',
    odds: '1 em 26.472.637',
    apiName: 'timemania',
    isBrazilian: true,
  },
  {
    slug: 'dupla-sena',
    name: 'Dupla Sena',
    country: 'Brasil',
    countryCode: 'BR',
    flag: '🇧🇷',
    emoji: '🎲',
    gradient: 'linear-gradient(135deg, #dc2626, #b91c1c)',
    color: '#dc2626',
    mainNumbers: 6,
    mainRange: [1, 50],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 2.50,
    currency: 'BRL',
    drawDays: ['terça', 'quinta', 'sábado'],
    drawTime: '20:00',
    timezone: 'America/Sao_Paulo',
    description: 'Duas chances de ganhar no mesmo concurso! Escolha 6 números de 1 a 50.',
    howToPlay: 'Escolha 6 números de 1 a 50. São feitos dois sorteios no mesmo concurso, dobrando suas chances!',
    jackpotStart: 'R$ 500.000',
    odds: '1 em 15.890.700',
    apiName: 'duplasena',
    isBrazilian: true,
  },
  {
    slug: 'dia-de-sorte',
    name: 'Dia de Sorte',
    country: 'Brasil',
    countryCode: 'BR',
    flag: '🇧🇷',
    emoji: '☀️',
    gradient: 'linear-gradient(135deg, #eab308, #facc15)',
    color: '#eab308',
    mainNumbers: 7,
    mainRange: [1, 31],
    extraNumbers: 0,
    extraRange: [0, 0],
    extraName: '',
    extraColor: 'green',
    pricePerBet: 2.50,
    currency: 'BRL',
    drawDays: ['terça', 'quinta', 'sábado'],
    drawTime: '20:00',
    timezone: 'America/Sao_Paulo',
    description: 'Escolha 7 números e um mês da sorte!',
    howToPlay: 'Escolha 7 números de 1 a 31 e um mês da sorte. Prêmios para 4 a 7 acertos e pelo mês sorteado.',
    jackpotStart: 'R$ 300.000',
    odds: '1 em 2.629.575',
    apiName: 'diadesorte',
    isBrazilian: true,
  },

  // ========== INTERNACIONAIS ==========
  {
    slug: 'powerball',
    name: 'Powerball',
    country: 'E.U.A.',
    countryCode: 'US',
    flag: '🇺🇸',
    emoji: '💥',
    gradient: 'linear-gradient(135deg, #dc2626, #ef4444)',
    color: '#dc2626',
    mainNumbers: 5,
    mainRange: [1, 69],
    extraNumbers: 1,
    extraRange: [1, 26],
    extraName: 'Powerball',
    extraColor: 'red',
    pricePerBet: 15.00,
    currency: 'BRL',
    drawDays: ['segunda', 'quarta', 'sábado'],
    drawTime: '23:59',
    timezone: 'America/New_York',
    description: 'A loteria mais famosa do mundo! Jackpots que ultrapassam bilhões de dólares.',
    howToPlay: 'Escolha 5 números de 1 a 69 e 1 Powerball de 1 a 26. Acerte todos para ganhar o jackpot!',
    jackpotStart: 'US$ 20.000.000',
    odds: '1 em 292.201.338',
    isBrazilian: false,
  },
  {
    slug: 'mega-millions',
    name: 'Mega Millions',
    country: 'E.U.A.',
    countryCode: 'US',
    flag: '🇺🇸',
    emoji: '💰',
    gradient: 'linear-gradient(135deg, #1d4ed8, #2563eb)',
    color: '#1d4ed8',
    mainNumbers: 5,
    mainRange: [1, 70],
    extraNumbers: 1,
    extraRange: [1, 25],
    extraName: 'Mega Ball',
    extraColor: 'gold',
    pricePerBet: 15.00,
    currency: 'BRL',
    drawDays: ['terça', 'sexta'],
    drawTime: '23:00',
    timezone: 'America/New_York',
    description: 'Outra gigante americana! Jackpots recordes de mais de US$ 1 bilhão.',
    howToPlay: 'Escolha 5 números de 1 a 70 e 1 Mega Ball de 1 a 25.',
    jackpotStart: 'US$ 20.000.000',
    odds: '1 em 302.575.350',
    isBrazilian: false,
  },
  {
    slug: 'euromilhoes',
    name: 'EuroMilhões',
    country: 'Europa',
    countryCode: 'EU',
    flag: '🇪🇺',
    emoji: '⭐',
    gradient: 'linear-gradient(135deg, #0369a1, #0ea5e9)',
    color: '#0369a1',
    mainNumbers: 5,
    mainRange: [1, 50],
    extraNumbers: 2,
    extraRange: [1, 12],
    extraName: 'Estrela',
    extraColor: 'gold',
    pricePerBet: 15.00,
    currency: 'BRL',
    drawDays: ['terça', 'sexta'],
    drawTime: '21:00',
    timezone: 'Europe/Lisbon',
    description: 'A maior loteria da Europa! Jogada em 9 países europeus.',
    howToPlay: 'Escolha 5 números de 1 a 50 e 2 Estrelas de 1 a 12.',
    jackpotStart: '€ 17.000.000',
    odds: '1 em 139.838.160',
    isBrazilian: false,
  },
  {
    slug: 'eurojackpot',
    name: 'EuroJackpot',
    country: 'Europa',
    countryCode: 'EU',
    flag: '🇪🇺',
    emoji: '🏆',
    gradient: 'linear-gradient(135deg, #b45309, #d97706)',
    color: '#b45309',
    mainNumbers: 5,
    mainRange: [1, 50],
    extraNumbers: 2,
    extraRange: [1, 12],
    extraName: 'Euro Number',
    extraColor: 'gold',
    pricePerBet: 12.00,
    currency: 'BRL',
    drawDays: ['terça', 'sexta'],
    drawTime: '21:00',
    timezone: 'Europe/Berlin',
    description: 'A loteria pan-europeia! Jogada em 18 países.',
    howToPlay: 'Escolha 5 números de 1 a 50 e 2 Euro Numbers de 1 a 12.',
    jackpotStart: '€ 10.000.000',
    odds: '1 em 139.838.160',
    isBrazilian: false,
  },
  {
    slug: 'superenalotto',
    name: 'SuperEnalotto',
    country: 'Itália',
    countryCode: 'IT',
    flag: '🇮🇹',
    emoji: '🇮🇹',
    gradient: 'linear-gradient(135deg, #059669, #10b981)',
    color: '#059669',
    mainNumbers: 6,
    mainRange: [1, 90],
    extraNumbers: 1,
    extraRange: [1, 90],
    extraName: 'Jolly',
    extraColor: 'green',
    pricePerBet: 10.00,
    currency: 'BRL',
    drawDays: ['terça', 'quinta', 'sábado'],
    drawTime: '20:00',
    timezone: 'Europe/Rome',
    description: 'A loteria italiana com jackpots enormes!',
    howToPlay: 'Escolha 6 números de 1 a 90. O número Jolly é sorteado separadamente.',
    jackpotStart: '€ 2.000.000',
    odds: '1 em 622.614.630',
    isBrazilian: false,
  },
  {
    slug: 'uk-lotto',
    name: 'UK Lotto',
    country: 'Reino Unido',
    countryCode: 'GB',
    flag: '🇬🇧',
    emoji: '👑',
    gradient: 'linear-gradient(135deg, #4338ca, #6366f1)',
    color: '#4338ca',
    mainNumbers: 6,
    mainRange: [1, 59],
    extraNumbers: 1,
    extraRange: [1, 59],
    extraName: 'Bonus Ball',
    extraColor: 'blue',
    pricePerBet: 10.00,
    currency: 'BRL',
    drawDays: ['quarta', 'sábado'],
    drawTime: '20:00',
    timezone: 'Europe/London',
    description: 'A clássica loteria britânica!',
    howToPlay: 'Escolha 6 números de 1 a 59. O Bonus Ball é sorteado separadamente.',
    jackpotStart: '£ 2.000.000',
    odds: '1 em 45.057.474',
    isBrazilian: false,
  },
]

export function getLotteryBySlug(slug: string): LotteryConfig | undefined {
  return LOTTERIES.find(l => l.slug === slug)
}

export function getBrazilianLotteries(): LotteryConfig[] {
  return LOTTERIES.filter(l => l.isBrazilian)
}

export function getInternationalLotteries(): LotteryConfig[] {
  return LOTTERIES.filter(l => !l.isBrazilian)
}

export function formatCurrency(value: number, currency: string = 'BRL'): string {
  if (currency === 'BRL') return `R$ ${value.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`
  if (currency === 'USD') return `US$ ${value.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`
  if (currency === 'EUR') return `€ ${value.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`
  return `${value.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`
}
